### ISSUE TITLE
Running vpn-slice as a non-root user

### ISSUE THREAD

**Issue by jonathannaguin** [dlenski/vpn-slice#19]
Hello,

OpenConnect can be executed as a non-root user according to the documentation I found on the web (https://www.infradead.org/openconnect/nonroot.html), haven't tried yet myself, but seems like it could work as long as the interface is created before running OpenConnect.
Now, vpn-slice writes to the /ets/hosts file and adds routes, operations that usually are performed by root.

Is there a way we can execute vpn-slice without being root?

Thanks!

**Comment by dlenski** [comment]
> Now, vpn-slice writes to the /ets/hosts file and adds routes, operations that usually are performed by root.
> 
> Is there a way we can execute vpn-slice without being root?

Not that I can think of. You wouldn't want an unprivileged user to be able to do these operations in a system-wide way, would you?

> OpenConnect can be executed as a non-root user according to the documentation I found on the web…

When you run OpenConnect in non-root mode, it has to abide by the same restrictions, and so does the “normal”/non-slicey vpnc-script. When you run OpenConnect in non-root mode, you'll almost use it with https://github.com/cernekee/ocproxy, which causes OpenConnect to send traffic through a locally-created _proxy_ rather than modify the system-wide routing/DNS.

It achieves an effect that's similar to vpn-slice, but it can be more cumbersome because you have to use proxyfied aliases for all the ports you want to access (e.g. `localhost:5243` instead of `normal.web.server.com:80`).
