### ISSUE TITLE
vpn-slice is not creating /dev/net/tun

### ISSUE THREAD

**Issue by sprnza** [dlenski/vpn-slice#23]
Hi there!
Thanks for the script. But I'm not able to get it working for some reason. The problem is that vpnc-slice is not creating `/dev/net/tun` so it fails to run after a fresh boot. I try to create the interface manually using these commands:
```
mkdir -p /dev/net
mknod -m 0640 /dev/net/tun c 10 200
```
as it happens in the default vpnc-script. But after this I'm unable to connect with this error:
```
vpnc: can't initialise tunnel interface: Operation not permitted
```
The only way to connect using vpn-slice is to connect to VPN using default vpnc-script, disconnect from it and then connect using vpn-slice. It seems like I'm missing something obvious, but I've spent over 4 hours finding it. Please help.

**Comment by dlenski** [comment]
* What version are you using? (`vpn-slice --version`)
* Does `vpnc` work correctly with the “default” vpnc-script?
* How are you invoking `vpn-slice` exactly? What's the `vpnc` command-line or config file look like?
* And probably more importantly, what _OS_ are you using? On Linux `/dev/net/tun` should exist since boot… it doesn't need to be created or set up in any way.

**Comment by sprnza** [comment]
Never mind, the issue is some of my containers were not privileged and they were not able to connect to VPN, but one of them was configure properly and I had workaround mentioned above working.
The only thing that I still need to create /dev/net/tun manually though.

**Comment by dlenski** [comment]
Got it. Okay, let's move over to #24 to continue discussing… :ok_hand:
