### ISSUE TITLE
Support read-only /etc/hosts

### ISSUE THREAD

**Issue by st31ny** [dlenski/vpn-slice#79]
I am running vpn-slice with options `--no-host-names --no-ns-hosts`. Thus, it never edits `/etc/hosts`. However, I still get an error when my / partition is mounted read-only:
```
WARNING: Couldn't configure hosts provider: Cannot read/write /etc/hosts                                                                                                                         
Aborting because providers for hosts are required; use --help for more information
```

I commented the line line throwing the OSError in HostsFileProvider.__init__ and then my setup actually work. So I think, the write access to /etc/hosts should not be checked statically but rather just when the file actually needs to be changed.

**Comment by dlenski** [comment]
> I commented the line line throwing the OSError in HostsFileProvider.init and then my setup actually work. So I think, the write access to /etc/hosts should not be checked statically but rather just when the file actually needs to be changed.

The issue with that is that the errors will be reported in a very confusing way if `vpn-slice` doesn't try to access `/etc/hosts` until it's in the `reason=connect` hook. (See abb6d2b90b16daa2ce3e2cadadcbe71184539275, #35.)

Ideas…

1. Remove `hosts` from the "required" list in the special case of `--no-host-names --no-ns-hosts`.
2. Remove `hosts` from the "required" list, and instead print warnings when `hosts` would otherwise try to do things.

I think I like (1) better because the errors from (2) would be hard to find, and in the meantime `vpn-slice` would *not* be doing what the user reasonably expects.

**Comment by st31ny** [comment]
Yeah, I see, I agree, (1) seems to give better diagnosis to the user.

**Comment by st31ny** [comment]
I just tested the patch in 9edb1cb and I think it needs some adjustments:

- We need to test if `hosts` is actually provided before reporting it missing.
- The condition should be `args.ns_hosts` is `True` OR `args.host_names` (and the rest)
- On shutdown, `do_disconnect` tries to access `hosts`, even if it's not provided.

**Comment by st31ny** [comment]
I just opened a PR with a fix that works at least in my setup.
